---
# tasks file for nginx
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install Nginx
  yum:
    name: nginx
    state: present
  notify: start nginx

- name: Enable systemd service
  systemd:
    name: nginx
    enabled: yes
